source 'https://rubygems.org'

ruby '2.7.0'

gem 'puma'
gem 'sinatra'
gem 'typhoeus'
gem 'pry'
gem 'redis'
gem 'faye'
gem 'permessage_deflate'

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
end